#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: CD

on:
  push:
    branches:
      - master
      - 'releases/**'
#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all
#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------------
  # build and test packages
  #----------------------------------------------------------------------------------
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install depdencies
        run: |
          npm install
          npx lerna bootstrap
      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        run:  npm run build
      #------------------------------------------------------------------------------
      # lint
      #------------------------------------------------------------------------------
      - name: Lint check
        run:  npm run lint
      #------------------------------------------------------------------------------
      # test
      #------------------------------------------------------------------------------
      - name: Intergation and unit tests
        run:  npm run test
      #------------------------------------------------------------------------------
      # artifacts
      #------------------------------------------------------------------------------
      - name: Archive node modules and build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            packages/**/dist/
            !node_modules
  #----------------------------------------------------------------------------------
  # deploy storybook
  #----------------------------------------------------------------------------------
  storybook:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
      - uses: chromaui/action@v1
        with:
          workingDir: ./packages/@mikoshi/storybook
          storybookBuildDir: dist
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
