#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Deployments

on:
  push:
    branches:
      - master
      - 'releases/**'
#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all
#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------------
  # build and test packages
  #----------------------------------------------------------------------------------
  build:
    name: Build and Test Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install depdencies
        run: |
          npm install
          npx lerna bootstrap
      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run:  npm run build
      #------------------------------------------------------------------------------
      # lint
      #------------------------------------------------------------------------------
      - name: Lint check
        run:  npm run lint
      #------------------------------------------------------------------------------
      # test
      #------------------------------------------------------------------------------
      - name: Intergation and unit tests
        run:  npm run test
      #------------------------------------------------------------------------------
      # publish packages
      #------------------------------------------------------------------------------
      - name: Publish packages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        run: |
          lerna publish from-package --yes --no-verify-access

      #------------------------------------------------------------------------------
      # deploy storybook
      #------------------------------------------------------------------------------
      - name: Deploy storybook
        run: npm run deploy:storybook -- --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded
