#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Integrations

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths-ignore: [doc/**]

#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all

#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------------
  # check the title of pull request
  #----------------------------------------------------------------------------------
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Verify pull request
    steps:
      - name: Verify pull request title match standard
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(chore|fix|feat|feat\(breaking\))+: ([a-z])+'
          allowed_prefixes: 'feat,fix,chore,fest(breaking)'
          disallowed_prefixes: 'feat/,hotfix'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 120
          github_token: ${{ github.token }}

  #----------------------------------------------------------------------------------
  # build packges and apps
  #----------------------------------------------------------------------------------
  build:
    name: Build packages and apps
    needs: validate-pull-request
    runs-on: ubuntu-latest
    env:
          NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x

      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install dependencies
        run: |
          pnpm install

      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run:  npm run build

      #------------------------------------------------------------------------------
      # cache build
      #------------------------------------------------------------------------------
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
            packages/**/dist/
            !packages/**/node_modules/dist/
          key: ${{ runner.os }}-mikoshi-${{ github.run_id }}
  
  #------------------------------------------------------------------------------
  # lint
  #------------------------------------------------------------------------------
  lint:
    runs-on: ubuntu-latest
    name: Source code lint check
    needs: build
    steps:
      - uses: actions/checkout@v3

      #------------------------------------------------------------------------------
      # retrieve cache
      #------------------------------------------------------------------------------
      - name: Retrieve cached build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
            packages/**/dist/
            !packages/**/node_modules/dist/
          key: ${{ runner.os }}-mikoshi-${{ github.run_id }}

      - run:  npm run lint

  #------------------------------------------------------------------------------
  # test
  #------------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    name: Integration and unit tests
    needs: build
    steps:
      - uses: actions/checkout@v3

      #------------------------------------------------------------------------------
      # retrieve cache
      #------------------------------------------------------------------------------
      - name: Retrieve cached build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
            packages/**/dist/
            !packages/**/node_modules/dist/
          key: ${{ runner.os }}-mikoshi-${{ github.run_id }}

      - run:  npm run test
