#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: Integrations

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths-ignore: [doc/**]

permissions: read-all

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Verify pull request
    steps:
      - name: Verify pull request title match standard
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(chore|fix|feat|feat\(breaking\))+: ([a-z])+'
          allowed_prefixes: 'feat,fix,chore,fest(breaking)'
          disallowed_prefixes: 'feat/,hotfix'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 120
          github_token: ${{ github.token }}

  ci:
    name: Build, Lint, and Test
    needs: validate-pull-request
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
