#------------------------------------------------------------------------------------
# Workflow configuration
#------------------------------------------------------------------------------------
name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths-ignore: [doc/**]
#------------------------------------------------------------------------------------
# Define application permissions & version
#------------------------------------------------------------------------------------
permissions: read-all
#------------------------------------------------------------------------------------
# Workflow jobs (Linux only)
#------------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------------
  # check the title of pull request
  #----------------------------------------------------------------------------------
  validate-pull-request:
    runs-on: ubuntu-latest
    name: Verify Pull Request
    steps:
      - name: PR Title Check
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(chore|feature|fix)+: ([a-z])+'
          allowed_prefixes: 'feature,fix,chore'
          disallowed_prefixes: 'feat/,hotfix'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 80
          github_token: ${{ github.token }}
  #----------------------------------------------------------------------------------
  # build and test packages
  #----------------------------------------------------------------------------------
  build:
    name: Build Packages
    needs: validate-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #------------------------------------------------------------------------------
      # install
      #------------------------------------------------------------------------------
      - name: Install depdencies
        run: |
          npm install
          npx lerna bootstrap
      #------------------------------------------------------------------------------
      # build
      #------------------------------------------------------------------------------
      - name: Build packages
        run:  npm run build
      #------------------------------------------------------------------------------
      # lint
      #------------------------------------------------------------------------------
      - name: Lint check
        run:  npm run lint
      #------------------------------------------------------------------------------
      # test
      #------------------------------------------------------------------------------
      - name: Intergation and unit tests
        run:  npm run test
